MainSaite/Controllers/AddressController.cs
using BAL.Manager;
using Common.Enum;
using DAL;
using Model;
using Model.DTO;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MainSaite.Controllers
{
    public class AddressController : BaseController
    {
		private IAddressManager addressmanager;
		public AddressController(IAddressManager addressmanager)
		{
			this.addressmanager = addressmanager;
		}

        public ActionResult Index()
        {
			return View();
        }

		public JsonResult GetFavoriteAddresses()
		{
			var addresses = addressmanager.GetAddressesForUser(SessionUser.Id);
			return Json(addresses, JsonRequestBehavior.AllowGet);
		}

		public void DelAddress(int addressId)
		{
			addressmanager.DeleteAddress(addressId);
		}

		public void UpdAddress(AddressDTO address)
		{
			addressmanager.UpdAddress(address);
		}


		public void AddAddress(AddressDTO address)
		{
			address.UserId = SessionUser.Id;
			addressmanager.AddAddress(address);
		}
    }
}

MainSaite/Views/Address/Index.cshtml
@Scripts.Render("~/Scripts/jquery-1.9.1.min.js")
@Scripts.Render("~/Scripts/handlebars.min.js")
@Scripts.Render("~/Scripts/moment.js")
@Scripts.Render("~/Scripts/HandlebarsCustomHelpers.js")
@Scripts.Render("~/Scripts/FavoriteAddresses.js")
@Scripts.Render("~/Scripts/sweetalert2.min.js")


@Styles.Render("~/Content/sweetalert2")

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="	background-color: #5bc0de; color: white;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">@Resources.Resource.FavAdr</h4>
            </div>
            <div class="modal-body">
                    <table class="table table-hover">
                        <tr class="form-group">
                            <td class="td-ench"><label class="control-label">@Resources.Resource.City</label></td>
                            <td>
                                <input id="newInputCarId" value="" hidden>
                                <input type="text" class="form-control input-lg" id="newCity" placeholder="@Resources.Resource.City" required>
                            </td>
                        </tr>
                        <tr class="form-group">
                            <td class="td-ench"><label class="control-label">@Resources.Resource.Street</label></td>
                            <td>
                                <input id="newInputCarId" value="" hidden>
                                <input type="text" class="form-control input-lg" id="newStreet" placeholder="@Resources.Resource.Street" required>
                            </td>
                        </tr>
                        <tr class="form-group">
                            <td class="td-ench"><label class="control-label">@Resources.Resource.Number</label></td>
                            <td>
                                <input id="newInputCarId" value="" hidden>
                                <input type="text" class="form-control input-lg" id="newNumber" placeholder="@Resources.Resource.Number" required>
                            </td>
                        </tr>
                        <tr class="form-group">
                            <td class="td-ench"><label class="control-label">@Resources.Resource.Comment</label></td>
                            <td>
                                <input id="newInputCarId" value="" hidden>
                                <input type="text" class="form-control input-lg" id="newComment" placeholder="@Resources.Resource.Comment" required>
                            </td>
                        </tr>

                    </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success addupd">Save changes</button>
            </div>
        </div>
    </div>
</div>


<div class="panel panel-info">
    <div class="panel-heading">
        <h3 style="text-align:center;">@Resources.Resource.TitleMainMenuAddress</h3>
    </div>

    <table class="table table-hover">
        <tr>
            <th>@Resources.Resource.City</th>
            <th>@Resources.Resource.Street</th>
            <th>@Resources.Resource.NumberHouse</th>
            <th>@Resources.Resource.Comment</th>
            <th style="width:215px">@Resources.Resource.Action</th>
        </tr>
        <tbody id="favorite"></tbody>
    </table>

    <script id="favorite-template" type="text/x-handlebars-template">
        {{#each addresses}}
        <tr>
            <td id="city{{AddressId}}">{{City}}</td>
            <td id="street{{AddressId}}">{{Street}}</td>
            <td id="number{{AddressId}}">{{Number}}</td>
            <td id="comment{{AddressId}}">{{Comment}}</td>
            <td>
                <button class="btn btn-primary edit" data-idaddress="{{AddressId}}" data-toggle="modal" data-target=".bs-example-modal-sm"><span>@Resources.Resource.editString</span></button>
                <button class="btn btn-warning del" data-idaddress="{{AddressId}}"><span>@Resources.Resource.deleteString</span></button>
            </td>
        </tr>

        {{/each}}
    </script>
</div>


<button class="btn btn-success edit" data-idaddress="-1"><span>@Resources.Resource.addString</span></button>

<script>
    var myurl = '@Url.Action("GetFavoriteAddresses", "Address")';
    var LocStrings = {
        Yes: '@Resources.Resource.Yes',
        AreYouSure: '@Resources.Resource.AreYouSure',
        No: '@Resources.Resource.No',
        YourAddressHasBeenDeleted: '@Resources.Resource.YourAddressHasBeenDeleted'
    }
</script>